
#define CAMERA_PIN_PWDN 26
#define CAMERA_PIN_RESET -1
#define CAMERA_PIN_XCLK 32
#define CAMERA_PIN_SIOD 13
#define CAMERA_PIN_SIOC 12
#define CAMERA_PIN_VSYNC 27
#define CAMERA_PIN_HREF 25
#define CAMERA_PIN_PCLK 19
#define CAMERA_PIN_Y2 5
#define CAMERA_PIN_Y3 14
#define CAMERA_PIN_Y4 4
#define CAMERA_PIN_Y5 15
#define CAMERA_PIN_Y6 18
#define CAMERA_PIN_Y7 23
#define CAMERA_PIN_Y8 36
#define CAMERA_PIN_Y9 39
