; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
lib_deps =
    ArduinoJson @ 7.4.2
    WebSockets @ 2.7.3
build_flags = 
    ; 设置日志级别
    ; - 0: 无日志 (ESP_LOG_NONE)
    ; - 1: 错误 (ESP_LOG_ERROR)
    ; - 2: 警告 (ESP_LOG_WARN)
    ; - 3: 信息 (ESP_LOG_INFO)
    ; - 4: 调试 (ESP_LOG_DEBUG)
    -DCORE_DEBUG_LEVEL=0
