
//
// ESP Speech Recognition
//
#define CONFIG_USE_WAKENET 1
#define CONFIG_SR_WN_MODEL_WN5_QUANT 1
#define CONFIG_SR_WN_WN5_HILEXIN 1
// CONFIG_SR_WN_WN5X2_HILEXIN is not set
// CONFIG_SR_WN_WN5X3_HILEXIN is not set
// CONFIG_SR_WN_WN5_NIHAOXIAOZHI is not set
// CONFIG_SR_WN_WN5X2_NIHAOXIAOZHI is not set
// CONFIG_SR_WN_WN5X3_NIHAOXIAOZHI is not set
// CONFIG_SR_WN_WN5X3_NIHAOXIAOXIN is not set
// CONFIG_SR_WN_WN5_CUSTOMIZED_WORD is not set
#define CONFIG_USE_MULTINET 1
#define CONFIG_SR_MN_CHINESE 1
#define CONFIG_SR_MN_CN_MULTINET2_SINGLE_RECOGNITION 1

//
// Add speech commands
//
#define CONFIG_CN_SPEECH_COMMAND_ID0 "da kai kong tiao"
#define CONFIG_CN_SPEECH_COMMAND_ID1 "guan bi kong tiao"
#define CONFIG_CN_SPEECH_COMMAND_ID2 "zeng da feng su"
#define CONFIG_CN_SPEECH_COMMAND_ID3 "jian xiao feng su"
#define CONFIG_CN_SPEECH_COMMAND_ID4 "sheng gao yi du"
#define CONFIG_CN_SPEECH_COMMAND_ID5 "jiang di yi du"
#define CONFIG_CN_SPEECH_COMMAND_ID6 "zhi re mo shi"
#define CONFIG_CN_SPEECH_COMMAND_ID7 "zhi leng mo shi"
#define CONFIG_CN_SPEECH_COMMAND_ID8 "song feng mo shi"
#define CONFIG_CN_SPEECH_COMMAND_ID9 "jie neng mo shi"
#define CONFIG_CN_SPEECH_COMMAND_ID10 "chu shi mo shi"
#define CONFIG_CN_SPEECH_COMMAND_ID11 "jian kang mo shi"
#define CONFIG_CN_SPEECH_COMMAND_ID12 "shui mian mo shi"
#define CONFIG_CN_SPEECH_COMMAND_ID13 "da kai lan ya"
#define CONFIG_CN_SPEECH_COMMAND_ID14 "guan bi lan ya"
#define CONFIG_CN_SPEECH_COMMAND_ID15 "kai shi bo fang"
#define CONFIG_CN_SPEECH_COMMAND_ID16 "zan ting bo fang"
#define CONFIG_CN_SPEECH_COMMAND_ID17 "ding shi yi xiao shi"
#define CONFIG_CN_SPEECH_COMMAND_ID18 "da kai dian deng"
#define CONFIG_CN_SPEECH_COMMAND_ID19 "guan bi dian deng"
#define CONFIG_CN_SPEECH_COMMAND_ID20 ""
#define CONFIG_CN_SPEECH_COMMAND_ID21 ""
#define CONFIG_CN_SPEECH_COMMAND_ID22 ""
#define CONFIG_CN_SPEECH_COMMAND_ID23 ""
#define CONFIG_CN_SPEECH_COMMAND_ID24 ""
#define CONFIG_CN_SPEECH_COMMAND_ID25 ""
#define CONFIG_CN_SPEECH_COMMAND_ID26 ""
#define CONFIG_CN_SPEECH_COMMAND_ID27 ""
#define CONFIG_CN_SPEECH_COMMAND_ID28 ""
#define CONFIG_CN_SPEECH_COMMAND_ID29 ""
#define CONFIG_CN_SPEECH_COMMAND_ID30 ""
#define CONFIG_CN_SPEECH_COMMAND_ID31 ""
#define CONFIG_CN_SPEECH_COMMAND_ID32 ""
#define CONFIG_CN_SPEECH_COMMAND_ID33 ""
#define CONFIG_CN_SPEECH_COMMAND_ID34 ""
#define CONFIG_CN_SPEECH_COMMAND_ID35 ""
#define CONFIG_CN_SPEECH_COMMAND_ID36 ""
#define CONFIG_CN_SPEECH_COMMAND_ID37 ""
#define CONFIG_CN_SPEECH_COMMAND_ID38 ""
#define CONFIG_CN_SPEECH_COMMAND_ID39 ""
#define CONFIG_CN_SPEECH_COMMAND_ID40 ""
#define CONFIG_CN_SPEECH_COMMAND_ID41 ""
#define CONFIG_CN_SPEECH_COMMAND_ID42 ""
#define CONFIG_CN_SPEECH_COMMAND_ID43 ""
#define CONFIG_CN_SPEECH_COMMAND_ID44 ""
#define CONFIG_CN_SPEECH_COMMAND_ID45 ""
#define CONFIG_CN_SPEECH_COMMAND_ID46 ""
#define CONFIG_CN_SPEECH_COMMAND_ID47 ""
#define CONFIG_CN_SPEECH_COMMAND_ID48 ""
#define CONFIG_CN_SPEECH_COMMAND_ID49 ""
#define CONFIG_CN_SPEECH_COMMAND_ID50 ""
#define CONFIG_CN_SPEECH_COMMAND_ID51 ""
#define CONFIG_CN_SPEECH_COMMAND_ID52 ""
#define CONFIG_CN_SPEECH_COMMAND_ID53 ""
#define CONFIG_CN_SPEECH_COMMAND_ID54 ""
#define CONFIG_CN_SPEECH_COMMAND_ID55 ""
#define CONFIG_CN_SPEECH_COMMAND_ID56 ""
#define CONFIG_CN_SPEECH_COMMAND_ID57 ""
#define CONFIG_CN_SPEECH_COMMAND_ID58 ""
#define CONFIG_CN_SPEECH_COMMAND_ID59 ""
#define CONFIG_CN_SPEECH_COMMAND_ID60 ""
#define CONFIG_CN_SPEECH_COMMAND_ID61 ""
#define CONFIG_CN_SPEECH_COMMAND_ID62 ""
#define CONFIG_CN_SPEECH_COMMAND_ID63 ""
#define CONFIG_CN_SPEECH_COMMAND_ID64 ""
#define CONFIG_CN_SPEECH_COMMAND_ID65 ""
#define CONFIG_CN_SPEECH_COMMAND_ID66 ""
#define CONFIG_CN_SPEECH_COMMAND_ID67 ""
#define CONFIG_CN_SPEECH_COMMAND_ID68 ""
#define CONFIG_CN_SPEECH_COMMAND_ID69 ""
#define CONFIG_CN_SPEECH_COMMAND_ID70 ""
#define CONFIG_CN_SPEECH_COMMAND_ID71 ""
#define CONFIG_CN_SPEECH_COMMAND_ID72 ""
#define CONFIG_CN_SPEECH_COMMAND_ID73 ""
#define CONFIG_CN_SPEECH_COMMAND_ID74 ""
#define CONFIG_CN_SPEECH_COMMAND_ID75 ""
#define CONFIG_CN_SPEECH_COMMAND_ID76 ""
#define CONFIG_CN_SPEECH_COMMAND_ID77 ""
#define CONFIG_CN_SPEECH_COMMAND_ID78 ""
#define CONFIG_CN_SPEECH_COMMAND_ID79 ""
#define CONFIG_CN_SPEECH_COMMAND_ID80 ""
#define CONFIG_CN_SPEECH_COMMAND_ID81 ""
#define CONFIG_CN_SPEECH_COMMAND_ID82 ""
#define CONFIG_CN_SPEECH_COMMAND_ID83 ""
#define CONFIG_CN_SPEECH_COMMAND_ID84 ""
#define CONFIG_CN_SPEECH_COMMAND_ID85 ""
#define CONFIG_CN_SPEECH_COMMAND_ID86 ""
#define CONFIG_CN_SPEECH_COMMAND_ID87 ""
#define CONFIG_CN_SPEECH_COMMAND_ID88 ""
#define CONFIG_CN_SPEECH_COMMAND_ID89 ""
#define CONFIG_CN_SPEECH_COMMAND_ID90 ""
#define CONFIG_CN_SPEECH_COMMAND_ID91 ""
#define CONFIG_CN_SPEECH_COMMAND_ID92 ""
#define CONFIG_CN_SPEECH_COMMAND_ID93 ""
#define CONFIG_CN_SPEECH_COMMAND_ID94 ""
#define CONFIG_CN_SPEECH_COMMAND_ID95 ""
#define CONFIG_CN_SPEECH_COMMAND_ID96 ""
#define CONFIG_CN_SPEECH_COMMAND_ID97 ""
#define CONFIG_CN_SPEECH_COMMAND_ID98 ""
#define CONFIG_CN_SPEECH_COMMAND_ID99 ""
// end of Add speech commands
// end of ESP Speech Recognition

//
// ESP-WHO Configuration
//

//
// Wi-Fi Configuration
//
#define CONFIG_ESP_HOST_NAME ""
#define CONFIG_ESP_WIFI_SSID ""
#define CONFIG_ESP_WIFI_PASSWORD ""
#define CONFIG_ESP_WIFI_AP_SSID "ESP32-Camera"
#define CONFIG_ESP_WIFI_AP_PASSWORD ""
#define CONFIG_MAX_STA_CONN 1
#define CONFIG_ESP_WIFI_AP_CHANNEL ""
#define CONFIG_SERVER_IP "192.168.4.1"
#define CONFIG_ESP_MAXIMUM_RETRY 5
// end of Wi-Fi Configuration

//
// Camera Configuration
//
// CONFIG_CAMERA_MODULE_WROVER_KIT is not set
// CONFIG_CAMERA_MODULE_ESP_EYE is not set
// CONFIG_CAMERA_MODULE_ESP_S2_KALUGA is not set
// CONFIG_CAMERA_MODULE_ESP_S3_EYE is not set
// CONFIG_CAMERA_MODULE_ESP32_CAM_BOARD is not set
// CONFIG_CAMERA_MODULE_M5STACK_PSRAM is not set
// CONFIG_CAMERA_MODULE_M5STACK_WIDE is not set
// CONFIG_CAMERA_MODULE_AI_THINKER is not set
#define CONFIG_CAMERA_MODULE_CUSTOM 1
#define CONFIG_CAMERA_PIN_PWDN 26
#define CONFIG_CAMERA_PIN_RESET -1
#define CONFIG_CAMERA_PIN_XCLK 32
#define CONFIG_CAMERA_PIN_SIOD 13
#define CONFIG_CAMERA_PIN_SIOC 12
#define CONFIG_CAMERA_PIN_VSYNC 27
#define CONFIG_CAMERA_PIN_HREF 25
#define CONFIG_CAMERA_PIN_PCLK 19
#define CONFIG_CAMERA_PIN_Y2 5
#define CONFIG_CAMERA_PIN_Y3 14
#define CONFIG_CAMERA_PIN_Y4 4
#define CONFIG_CAMERA_PIN_Y5 15
#define CONFIG_CAMERA_PIN_Y6 18
#define CONFIG_CAMERA_PIN_Y7 23
#define CONFIG_CAMERA_PIN_Y8 36
#define CONFIG_CAMERA_PIN_Y9 39
// end of Camera Configuration

//
// Model Configuration
//

//
// Face Recognition
//
#define CONFIG_MFN_V1 1
#define CONFIG_S8 1
// CONFIG_S16 is not set
// end of Face Recognition
// end of Model Configuration
// end of ESP-WHO Configuration
