
#define UART_NUM UART_NUM_2
#define UART_BUFFER_LENGTH 1024*4
#define UART_TX_PIN 21
#define UART_RX_PIN 22

#define DATA_LENGTH 512

#define STORAGE_NAMESPADE "ESP_AI_CAM"

#define TAG "ESP AI CAM"

#define AI_MODE_CONFIG 1
#define AI_MODE_CAT_FACE_DETECTION    1
#define AI_MODE_CODE_RECOGNITION      2
#define AI_MODE_COLOR_DETECTION       3
#define AI_MODE_HUMAN_FACE_DETECTION  4
#define AI_MODE_HUMAN_FACE_RECOGITION 5
#define AI_MODE_MOTION_DETECTION      6

#define VFLIP 0