
#define I2C_SLAVE_NUM 0
#define I2C_SLAVE_SDA_IO 21
#define I2C_SLAVE_SCL_IO 22
#define DATA_LENGTH 512
#define I2C_SLAVE_TX_BUF_LEN (2 * DATA_LENGTH) // I2C slave tx buffer size
#define I2C_SLAVE_RX_BUF_LEN (2 * DATA_LENGTH) // I2C slave rx buffer size

#define STORAGE_NAMESPADE "ESP_AI_CAM"

#define TAG "ESP AI CAM"

#define AI_MODE_CONFIG 1
#define AI_MODE_CAT_FACE_DETECTION    1
#define AI_MODE_CODE_RECOGNITION      2
#define AI_MODE_COLOR_DETECTION       3
#define AI_MODE_HUMAN_FACE_DETECTION  4
#define AI_MODE_HUMAN_FACE_RECOGITION 5
#define AI_MODE_MOTION_DETECTION      6

#define VFLIP 0